name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
